version: "3"

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./${DB_DIR-db-data}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  registry:
    image: dockerhub/sunbird-rc-core:${RELEASE_VERSION}
    volumes:
      - ./${SCHEMA_DIR-import/schemas}:/home/sunbirdrc/config/public/_schemas
    environment:
      - connectionInfo_uri=jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
      - connectionInfo_username=${DB_USERNAME}
      - connectionInfo_password=${DB_PASSWORD}
      - search_providerName=${SEARCH_PROVIDER_NAME}
      - sunbird_sso_realm=${KEYCLOAK_REALM}
      - sunbird_sso_url=${KEYCLOAK_SSO_URL}
      - sunbird_sso_admin_client_id=${KEYCLOAK_ADMIN_CLIENT_ID}
      - sunbird_sso_client_id=${KEYCLOAK_CLIENT_ID}
      - sunbird_sso_admin_client_secret=${KEYCLOAK_SECRET}
      - signature_enabled=false
      - sunbird_keycloak_user_set_password=true
      - sunbird_keycloak_user_password=abcd@123
      - logging.level.root=INFO
      - enable_external_templates=false
      - async_enabled=${ASYNC_ENABLED}
      - authentication_enabled=false
      - manager_type=${MANAGER_TYPE}
#    ports:
#      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -nv -t1 --spider http://localhost:8081/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10
  keycloak:
    image: ghcr.io/sunbird-rc/event-engagement-demo/keycloak:latest
    volumes:
      - ./${KEYCLOAK_IMPORT_DIR}:/opt/jboss/keycloak/imports
      - ./${KEYCLOAK_THEMES_DIR}:/opt/jboss/keycloak/themes/nha
    environment:
      - KEYCLOAK_LOGO=https://raw.githubusercontent.com/Sunbird-RC/demo-donor-registry/main/imports/header_logo.svg
      - DB_VENDOR=postgres
      - DB_ADDR=${DB_URL}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_PORTAL_TITLE=
      - KEYCLOAK_PORTAL_SUB_TITLE=
      - SIGN_UP_LINK=/form/signup
      - SHOW_FOOTER=false
      - SHOW_BANNER=false
      - LOGIN_USER_ID_TITLE=Mobile Number
      - MOCK_OTP=true
      - MESSAGE_TEMPLATE=${MESSAGE_TEMPLATE}
      - REGISTER_URL=${REGISTER_URL}
      - INVALID_REGISTRATION=${INVALID_REGISTRATION}
      - INVALID_USERNAME=${INVALID_USERNAME}
      - VALID_OTP=${VALID_OTP}
      - OTP_MAX_RETRY_LIMIT=${OTP_MAX_RETRY_LIMIT}
      - MAX_RETRIES_LIMIT_MESSAGE=${MAX_RETRIES_LIMIT_MESSAGE}
      - MAX_RESEND_TRIES=${MAX_RESEND_TRIES}
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9990/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
#    ports:
#      - "8080:8080"
#      - "9990:9990"
    depends_on:
      db:
        condition: service_healthy
  event-engagement-service:
    image: ghcr.io/sunbird-rc/event-engagement-demo/event-engagement-service
    environment:
      - VISITOR_QR_BASE_URL="http://localhost:8000"
      - KEYCLOAK_URL=${KEYCLOAK_SSO_URL}
      - SERVICE_ACCOUNT_CLIENT_SECRET=${KEYCLOAK_SERVICE_ACCOUNT_CLIENT_SECRET}
      - registryUrl=${REGISTRY_URL}
      - credentialUrl=${CREDENTIAL_SERVICE_URL}
      - identityUrl=${IDENTITY_SERVICE_URL}
      - credentialSchemaUrl=${CREDENTIAL_SCHEMA_SERVICE_URL}
    healthcheck:
      test:
        [ "CMD-SHELL", "curl -f http://localhost:8000/swagger || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      registry:
        condition: service_healthy
  nginx:
    image: ghcr.io/sunbird-rc/event-engagement-demo/nginx-gateway
    ports:
      - "80:80"
    depends_on:
      registry:
        condition: service_healthy
      keycloak:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "localhost:80" ]
      interval: 30s
      timeout: 10s
      retries: 10
networks:
  default:
    external:
      name: rcw

